### ISSUE TITLE
New version for Xitrum 3.1

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum-scalate#7]
Xitrum 3.1 does not work with xitrum-scalate 1.5:

```
java.lang.NoClassDefFoundError: Lxitrum/scope/request/ReplaceableFullHttpResponse;
```
